dogs_cats/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from rest_framework import routers

app_name = 'dogs_cats'

# api router
router = routers.DefaultRouter()
router.register('dogs', views.DogViewSet)
router.register('cats', views.CatViewSet)


urlpatterns = [
    path('', views.SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='dogs_cats/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfilePage.as_view(), name='profile'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('create_dog/', views.CreateDog.as_view(), name='create_dog'),
    path('create_cat/', views.CreateCat.as_view(), name='create_cat'),
    path('list_dog/', views.ListDog.as_view(), name='list_dog'),
    path('list_dog/<int:pk>', views.DetailDog.as_view(), name='detail_dog'),
    path('list_cat/', views.ListCat.as_view(), name='list_cat'),
    path('list_cat/<int:pk>', views.DetailCat.as_view(), name='detail_cat'),
    path('update_dog/<int:pk>', views.UpdateDog.as_view(), name='update_dog'),
    path('update_cat/<int:pk>', views.UpdateCat.as_view(), name='update_cat'),
    path('delete_dog/<int:pk>', views.DeleteDog.as_view(), name='delete_dog'),
    path('delete_cat/<int:pk>', views.DeleteCat.as_view(), name='delete_cat'),
    path('api/', include(router.urls))
]

pets/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Homepage.as_view(), name='homepage'),
    path('dogs_cats/', include('dogs_cats.urls', namespace='dogs_cats')),
    path('dogs_cats/', include('django.contrib.auth.urls')),
]

dogs_cats/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User, PermissionsMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse


# Create your models here.


class RegUser(User, PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)


class Dog(models.Model):
    name = models.CharField(max_length=40)
    bday = models.DateField()
    owner = models.ForeignKey(User, related_name='dogs', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('dogs_cats:list_dog')

    def __str__(self):
        return self.name


class Cat(models.Model):
    name = models.CharField(max_length=40)
    bday = models.DateField()
    owner = models.ForeignKey(User, related_name='cats', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('dogs_cats:list_cat')

    def __str__(self):
        return self.name

dogs_cats/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username', 'password1', 'password2')
        model = get_user_model()


    def __init__(self, *args, **kwargs):
    	super().__init__(*args, **kwargs)
    	self.fields['username'].label = 'Username'

dogs_cats/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .forms import UserCreateForm
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Dog, Cat
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from rest_framework import viewsets
from .serializers import DogSerializer, CatSerializer


# Create your views here.


class SignUp(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'dogs_cats/signup.html'


class ProfilePage(TemplateView):
    template_name = 'dogs_cats/profile.html'


class ThanksPage(TemplateView):
    template_name = 'dogs_cats/thanks.html'


class CreateDog(CreateView):
    template_name = 'dogs_cats/create_dog.html'
    model = Dog
    fields = ('name', 'bday')

    # Assign the newly created dog to the current logged in user
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(CreateDog, self).form_valid(form)


class CreateCat(CreateView):
    template_name = 'dogs_cats/create_cat.html'
    model = Cat
    fields = ('name', 'bday')

     # Assign the newly created cat to the current logged in user
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(CreateCat, self).form_valid(form)


class ListDog(ListView):
    template_name = 'dogs_cats/list_dog.html'
    model = Dog
    queryset = Dog.objects.all()

    #List pet dogs under the current logged in user
    def get_queryset(self):
        return self.queryset.filter(owner=self.request.user)


class DetailDog(DetailView):
    template_name = 'dogs_cats/detail_dog.html'
    model = Dog
    context_object_name = 'dogs'


class ListCat(ListView):
    template_name = 'dogs_cats/list_cat.html'
    model = Cat
    queryset = Cat.objects.all()

    #List pet cats under the current logged in user
    def get_queryset(self):
        return self.queryset.filter(owner=self.request.user)


class DetailCat(DetailView):
    template_name = 'dogs_cats/detail_cat.html'
    model = Cat
    context_object_name = 'cats'


class UpdateDog(UpdateView):
    template_name = 'dogs_cats/update_dog.html'
    model = Dog
    fields = ('name', 'bday')


class UpdateCat(UpdateView):
    template_name = 'dogs_cats/update_cat.html'
    model = Cat
    fields = ('name', 'bday')


class DeleteDog(DeleteView):
    template_name = 'dogs_cats/delete_dog.html'
    model = Dog
    success_url = reverse_lazy('dogs_cats:list_dog')


class DeleteCat(DeleteView):
    template_name = 'dogs_cats/delete_cat.html'
    model = Cat
    success_url = reverse_lazy('dogs_cats:list_cat')


# DRF
class DogViewSet(viewsets.ModelViewSet):
    queryset = Dog.objects.all()
    serializer_class = DogSerializer

    def get_queryset(self):
        dog_owner = self.queryset.filter(owner=self.request.user)
        return dog_owner


class CatViewSet(viewsets.ModelViewSet):
    queryset = Cat.objects.all()
    serializer_class = CatSerializer

    def get_queryset(self):
        cat_owner = self.queryset.filter(owner=self.request.user)
        return cat_owner

pets/views.py
from django.views.generic import TemplateView



class Homepage(TemplateView):
	template_name = 'pets/homepage.html'

templates/dogs_cats/create_cat.html
{% extends 'dogs_cats/base.html' %}


{% block content %}
	
	<h2>Add Pet Cat</h2>

	<form method="POST">
		{% csrf_token %}

		{{ form.as_p }}

		<input type="submit" value="Add Pet Cat">
	</form>

	<a href="{% url 'dogs_cats:profile' %}">back</a>

{% endblock %}

templates/dogs_cats/create_dog.html
{% extends 'dogs_cats/base.html' %}


{% block content %}
	
	<h2>Add Dog Pet</h2>

	<form method="POST">
		{% csrf_token %}

		{{ form.as_p }}

		<input type="submit" value="Add Pet Dog">
	</form>

	<a href="{% url 'dogs_cats:profile' %}">back</a>

{% endblock %}

templates/dogs_cats/delete_cat.html
{% extends 'pets/base.html' %}

{% block content %}
	
	<h3>Are you sure? All information will be deleted.</h3>


	<form method="post">
		{% csrf_token %}
		

		<input type="submit" name="update" value="Yes, Delete This Info">
	</form>

	<a href="{% url 'dogs_cats:list_cat' %}">Back</a>

{% endblock %}

templates/dogs_cats/delete_dog.html
{% extends 'pets/base.html' %}

{% block content %}
	
	<h3>Are you sure? All information will be deleted.</h3>


	<form method="post">
		{% csrf_token %}
		

		<input type="submit" name="update" value="Yes, Delete This Info">
	</form>

	<a href="{% url 'dogs_cats:list_dog' %}">Back</a>

{% endblock %}

templates/dogs_cats/detail_cat.html
{% extends 'pets/base.html'  %}


{% block content %}

	<h2> Update or Delete Pet Information for {{ cats.name }} </h2>
	
	<ul>
		<li><h3>Name:  {{cats.name}}</h3></li>
		<li><h3>Bday:  {{cats.bday}}</h3></li>
	</ul>


	<a href="{% url 'dogs_cats:update_cat' pk=cats.pk %}">Update This Info</a><br/ >
	<a href="{% url 'dogs_cats:delete_cat' pk=cats.pk %}">Delete This Info</a><br />
	<a href="{% url 'dogs_cats:list_cat' %}">Back</a>



{% endblock %}

templates/dogs_cats/detail_dog.html
{% extends 'pets/base.html' %}


{% block content %}
	
	<h2> Update or Delete Pet Information for {{ dogs.name }} </h2>
	
	<ul>
		<li><h3>Name:  {{dogs.name}}</h3></li>
		<li><h3>Bday:  {{dogs.bday}}</h3></li>
	</ul>

	<a href="{% url 'dogs_cats:update_dog' pk=dogs.pk %}">Update This Info</a><br />
	<a href="{% url 'dogs_cats:delete_dog' pk=dogs.pk %}">Delete This Info</a><br />
	<a href="{% url 'dogs_cats:list_dog' %}">Back</a>

{% endblock %}

templates/dogs_cats/list_cat.html
{% extends 'pets/base.html' %}


{% block content %}

	<h2>Your Pets - Cat </h2>

	<ul>
		{% for cat in object_list %}

			<li><a href="{{ cat.id }}">Name: {{ cat.name }}</a></li>

		{% endfor %}
	</ul>

{% endblock %}

templates/dogs_cats/list_dog.html
{% extends 'pets/base.html' %}

{% block content %}
	
	<h2>Your Pets - Dog</h2>

	<ul>
		{% for dog in object_list %}
			<li><a href="{{ dog.id }}">Name: {{ dog.name }}</a></li>
		{% endfor %}
	</ul>

{% endblock %}

templates/dogs_cats/login.html
{% extends 'pets/base.html' %}



{% block content %}
	<h2>Login</h2>

	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}

		<input type="submit" value="Login">
	</form>

{% endblock %}

templates/dogs_cats/profile.html
{% extends 'pets/base.html' %}



{% block content %}
	

{% endblock %}

templates/dogs_cats/signup.html
{% extends 'pets/base.html' %}



{% block content %}
	<h2>Sign Up</h2>

	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}

		<input type="submit" value="Sign Up">
	</form>

{% endblock %}

templates/dogs_cats/thanks.html
{% extends 'pets/base.html' %}



{% block content %}
	<h2>Thanks for checking your pets, come back soon!</h2>
{% endblock %}

templates/dogs_cats/update_cat.html
{% extends 'pets/base.html' %}

{% block content %}
	

	<form method="post">
		{% csrf_token %}
		{{form.as_p}}

		<input type="submit" name="update" value="Update Info">
	</form>

	<a href="{% url 'dogs_cats:list_dog' %}">Back</a>

{% endblock %}

templates/dogs_cats/update_dog.html
{% extends 'pets/base.html' %}

{% block content %}
	

	<form method="post">
		{% csrf_token %}
		{{form.as_p}}

		<input type="submit" name="update" value="Update Info">
	</form>

	<a href="{% url 'dogs_cats:list_dog' %}">Back</a>

{% endblock %}

templates/pets/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Crowdbotics - Pets</title>
</head>
<body>

	<h2>Crowdbotics - Pets</h2>

	<ul>
	{% if user.is_authenticated %}
		<li><a href="{% url 'dogs_cats:logout' %}">Logout</a></li>
		<li><a href="{% url 'dogs_cats:create_dog' %}">Add Pet - Dog</li>
		<li><a href="{% url 'dogs_cats:create_cat' %}">Add Pet - Cat</a></li>
		<li><a href="{% url 'dogs_cats:list_dog' %}">View My Pets - Dog</a></li>
		<li><a href="{% url 'dogs_cats:list_cat' %}">View My Pets - Cat</a></li>
		<li><a href="/dogs_cats/api">Access My Pets' API</a></li>

	{% else %}
		<li><a href="{% url 'dogs_cats:signup' %}">SignUp</a></li>
		<li><a href="{% url 'dogs_cats:login' %}">Login</a></li>

	{% endif %}
	</ul>
	


	{% block content %}


	{% endblock %}

</body>
</html>

templates/pets/homepage.html
<!DOCTYPE html>
<html>
<head>
	<title>Crowdbotics - Exam</title>
</head>
<body>

	<h1>Crowdbotics - Pets</h1>

	{% if user.is_authenticated %}
		<a href="{% url 'dogs_cats:profile' %}">Access Your Profile</a>
	{% else %}
		<a href="{% url 'dogs_cats:signup' %}">Process To SignUp</a>
	{% endif %}
	

</body>
</html>